### ISSUE TITLE
Does not work on safe.duckduckgo.com

### ISSUE THREAD

**Issue by onguarde** [Sayak9495/DuckItUp#1]
great extension so far! 

would be nice if you can add hiding of search query in POST, when searching from omnibar.

**Comment by Sayak9495** [comment]
Hey @onguarde , Thank a lot. 
Will add safe.duckduckgo as well in manifest file.
And can you elaborate what exactly do you mean in your 2nd comment? 
`add hiding of search query in POST, when searching from omnibar.`

**Comment by Sayak9495** [comment]
This issue has been fixed by this commit - ebcba3f4789105b1f010877f06e53a96bab5ddba 
I'm going to close the issue. Please go ahead and reopen if needed.
