### ISSUE TITLE
Make this compatible with Firefox

### ISSUE THREAD

**Issue by arjunmahishi** [Sayak9495/DuckItUp#2]
This extension is pretty cool. Would love to use this in firefox.

Working on it. Will make a PR soon. 

Refering to [this](https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/)

**Comment by arjunmahishi** [comment]
Made a PR: #3

**Comment by Sayak9495** [comment]
Thanks for the PR. 
Working towards getting this extension published to Firefox as well
